### ISSUE TITLE
mvn clean install site - test fails with Stream closed

### ISSUE THREAD

**Issue by karianna** [samskivert/jmustache#159]
Hi there,

Was looking to make a quick contribution to the build scripts but on a clean run I got the following:

[INFO] Running com.samskivert.mustache.specs.OfficialSpecTest
*** Error loading: /specs/specs/comments.yml
*** You probably need to 'git submodule update'.
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.015 s <<< FAILURE! -- in com.samskivert.mustache.specs.OfficialSpecTest
[ERROR] com.samskivert.mustache.specs.OfficialSpecTest.initializationError -- Time elapsed: 0 s <<< ERROR!
org.yaml.snakeyaml.error.YAMLException: java.io.IOException: Stream closed
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:214)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:172)
	at org.yaml.snakeyaml.reader.StreamReader.ensureEnoughData(StreamReader.java:167)
	at org.yaml.snakeyaml.reader.StreamReader.peek(StreamReader.java:122)
	at org.yaml.snakeyaml.scanner.ScannerImpl.scanToNextToken(ScannerImpl.java:1204)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:320)
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:238)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseImplicitDocumentStart.produce(ParserImpl.java:212)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162)
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:152)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:156)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:178)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:434)
	at com.samskivert.jmustache@1.17-SNAPSHOT/com.samskivert.mustache.specs.SpecTest.getTestsFromYaml(SpecTest.java:100)
	at com.samskivert.jmustache@1.17-SNAPSHOT/com.samskivert.mustache.specs.SpecTest.getTestsForGroup(SpecTest.java:94)
	at com.samskivert.jmustache@1.17-SNAPSHOT/com.samskivert.mustache.specs.SpecTest.data(SpecTest.java:82)
	at com.samskivert.jmustache@1.17-SNAPSHOT/com.samskivert.mustache.specs.OfficialSpecTest.data(OfficialSpecTest.java:27)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.runners.Parameterized$RunnersFactory.allParameters(Parameterized.java:424)
	at org.junit.runners.Parameterized$RunnersFactory.<init>(Parameterized.java:375)
	at org.junit.runners.Parameterized$RunnersFactory.<init>(Parameterized.java:360)
	at org.junit.runners.Parameterized.<init>(Parameterized.java:303)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.requests.ClassRequest.createRunner(ClassRequest.java:28)
	at org.junit.internal.requests.MemoizingRequest.getRunner(MemoizingRequest.java:19)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:314)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.PushbackInputStream.ensureOpen(PushbackInputStream.java:82)
	at java.base/java.io.PushbackInputStream.read(PushbackInputStream.java:177)
	at org.yaml.snakeyaml.reader.UnicodeReader.init(UnicodeReader.java:85)
	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:117)
	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:179)
	... 44 more

**Comment by samskivert** [comment]
This would be the key line in that giant error:
```
*** You probably need to 'git submodule update'.
```

The tests bring in the standard Mustache tests via a git submodule, so once you clone the jmustache repository, you need to run `git submodule update` in the top-level project directory.

**Comment by karianna** [comment]
Hi, sorry for the late reply! I did actually try that, but no luck, running `git submodule update` gives me a no-op

```
martijnverburg@Martijns-MacBook-Pro jmustache % git submodule status
-83b221aec50adb91eeaa935ba7bd51cd792daece src/test/resources/specs
```

**Comment by reinhardtexah** [comment]
@karianna You first need to [initialize the submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules) after cloning the `jmustache` repository.

I ran the following commands, which worked:

```bash
git submodule init
git submodule update
```

The output:

```bash
git submodule update                  
Cloning into '../jmustache/src/test/resources/specs'...Submodule path 'src/test/resources/specs': checked out '83b221aec50adb91eeaa935ba7bd51cd792daece'
```

The `src/test/resources/specs` directory afterwards:

```bash
├── custom
│   └── specs
│       ├── partials.yml
│       ├── sections.yml
│       └── ~inheritance.yml
└── specs
    ├── Changes
    ├── LICENSE
    ├── README.md
    ├── Rakefile
    ├── TESTING.md
    └── specs
        ├── comments.json
        ├── comments.yml
        ├── delimiters.json
        ├── delimiters.yml
        ├── interpolation.json
        ├── interpolation.yml
        ├── inverted.json
        ├── inverted.yml
        ├── partials.json
        ├── partials.yml
        ├── sections.json
        ├── sections.yml
        ├── ~dynamic-names.json
        ├── ~dynamic-names.yml
        ├── ~inheritance.json
        ├── ~inheritance.yml
        ├── ~lambdas.json
        └── ~lambdas.yml

5 directories, 26 files
```
